In [1]:
# Importing the Required libraries 
import pandas as pd
import numpy as np
import os
import sys
import re
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score,accuracy_score,confusion_matrix
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import VarianceThreshold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import classification_report
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, f_classif
from sklearn.feature_selection import mutual_info_regression
from sklearn.feature_selection import SelectPercentile
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.exceptions import NotFittedError
from sklearn.dummy import DummyRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import HuberRegressor
import catboost as cb
from sklearn.neighbors import KNeighborsClassifier
from datetime import datetime

In [2]:
# Setting global options for the notebook such as maxrows
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_colwidth', None)
pd.set_option("display.max_rows", 100)
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Importing the Dataset 
path=os.getcwd()
# Assigning a path for the file 
NO2_file_path=path+"\\daily_NO2_2022.csv"
ozonefile_path=path+"\\daily_ozone_2022.csv"
CO_file_path=path+"\\daily_CO_2022.csv"
SO2_file_path=path+"\\daily_SO2_2022.csv"

file_path_88502=path+"\\daily_88502_2022.csv"
file_path_88101=path+"\\daily_88101_2022.csv"
file_path_81101=path+"\\daily_81102_2022.csv"
file_path_86101=path+"\\daily_86101_2022.csv"
file_path_PM10SPEC=path+"\\daily_PM10SPEC_2022.csv"
#file_path_SPEC=path+"\\daily_SPEC_2022.csv"
temp_file_path=path+"\\daily_TEMP_2022.csv"
press_file_path=path+"\\daily_PRESS_2022.csv"
wind_file_path=path+"\\daily_WIND_2022.csv"
RH_file_path=path+"\\daily_RH_DP_2022.csv"

In [4]:
# Loading the source file into Pandas DataFrame
NO2_df=pd.read_csv(NO2_file_path)
ozone_df=pd.read_csv(ozonefile_path)
CO_df=pd.read_csv(CO_file_path)
SO2_df=pd.read_csv(SO2_file_path)

df_88502=pd.read_csv(file_path_88502)
df_88101=pd.read_csv(file_path_88101)
df_81101=pd.read_csv(file_path_81101)
df_86101=pd.read_csv(file_path_86101)
df_PM10SPEC=pd.read_csv(file_path_PM10SPEC)
#df_SPEC=pd.read_csv(file_path_SPEC)
temp_df=pd.read_csv(temp_file_path)
press_df=pd.read_csv(press_file_path)
wind_df=pd.read_csv(wind_file_path)
RH_df=pd.read_csv(RH_file_path)

In [5]:
"""
df_88502=df_88502.dropna(subset = ['AQI'], inplace=True)
df_88101=df_88101.dropna(subset = ['AQI'], inplace=True)
df_81101=df_81101.dropna(subset = ['AQI'], inplace=True)
df_86101=df_86101.dropna(subset = ['AQI'], inplace=True)
df_PM10SPEC=df_PM10SPEC.dropna(subset = ['AQI'], inplace=True)
df_SPEC=df_SPEC.dropna(subset = ['AQI'], inplace=True)
"""

"\ndf_88502=df_88502.dropna(subset = ['AQI'], inplace=True)\ndf_88101=df_88101.dropna(subset = ['AQI'], inplace=True)\ndf_81101=df_81101.dropna(subset = ['AQI'], inplace=True)\ndf_86101=df_86101.dropna(subset = ['AQI'], inplace=True)\ndf_PM10SPEC=df_PM10SPEC.dropna(subset = ['AQI'], inplace=True)\ndf_SPEC=df_SPEC.dropna(subset = ['AQI'], inplace=True)\n"

In [6]:
NO2_df.head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,Pollutant Standard,Date Local,Units of Measure,Event Type,Observation Count,Observation Percent,Arithmetic Mean,1st Max Value,1st Max Hour,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
0,1,73,23,42602,1,33.553056,-86.815,WGS84,Nitrogen dioxide (NO2),1 HOUR,NO2 1-hour 2010,2022-01-01,Parts per billion,None,24,100.0,1.308333,1.9,12,1,200,Teledyne-API Model 200EUP or T200UP - Photolytic-Chemiluminescence,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2023-03-16
1,1,73,23,42602,1,33.553056,-86.815,WGS84,Nitrogen dioxide (NO2),1 HOUR,NO2 1-hour 2010,2022-01-02,Parts per billion,None,24,100.0,1.954167,4.2,9,4,200,Teledyne-API Model 200EUP or T200UP - Photolytic-Chemiluminescence,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2023-03-16
2,1,73,23,42602,1,33.553056,-86.815,WGS84,Nitrogen dioxide (NO2),1 HOUR,NO2 1-hour 2010,2022-01-03,Parts per billion,None,10,42.0,1.530000,2.2,0,2,200,Teledyne-API Model 200EUP or T200UP - Photolytic-Chemiluminescence,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2023-03-16
3,1,73,23,42602,1,33.553056,-86.815,WGS84,Nitrogen dioxide (NO2),1 HOUR,NO2 1-hour 2010,2022-01-04,Parts per billion,None,9,38.0,5.455556,8.1,22,8,200,Teledyne-API Model 200EUP or T200UP - Photolytic-Chemiluminescence,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2023-03-16
4,1,73,23,42602,1,33.553056,-86.815,WGS84,Nitrogen dioxide (NO2),1 HOUR,NO2 1-hour 2010,2022-01-05,Parts per billion,None,16,67.0,16.493750,29.4,18,27,200,Teledyne-API Model 200EUP or T200UP - Photolytic-Chemiluminescence,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2023-03-16

In [7]:
ozone_df.head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,Pollutant Standard,Date Local,Units of Measure,Event Type,Observation Count,Observation Percent,Arithmetic Mean,1st Max Value,1st Max Hour,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
0,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-02-28,Parts per million,None,1,6.0,0.038000,0.038,23,35,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2023-04-27
1,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-03-01,Parts per million,None,17,100.0,0.037235,0.054,12,50,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2023-04-27
2,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-03-02,Parts per million,None,17,100.0,0.038235,0.055,12,51,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2023-04-27
3,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-03-03,Parts per million,None,9,53.0,0.024333,0.043,15,40,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2023-04-27
4,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-03-04,Parts per million,None,17,100.0,0.049647,0.063,10,77,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2023-04-27

In [8]:
#concat_df1=pd.concat([NO2_df,ozone_df,CO_df,SO2_df])
concat_df1=pd.concat([ozone_df])
#concat_df1=pd.concat([NO2_df,ozone_df,CO_df,SO2_df,df_88502,df_88101,df_81101,df_86101,df_PM10SPEC,df_SPEC])

In [9]:
concat_df1.head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,Pollutant Standard,Date Local,Units of Measure,Event Type,Observation Count,Observation Percent,Arithmetic Mean,1st Max Value,1st Max Hour,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
0,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-02-28,Parts per million,None,1,6.0,0.038000,0.038,23,35,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2023-04-27
1,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-03-01,Parts per million,None,17,100.0,0.037235,0.054,12,50,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2023-04-27
2,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-03-02,Parts per million,None,17,100.0,0.038235,0.055,12,51,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2023-04-27
3,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-03-03,Parts per million,None,9,53.0,0.024333,0.043,15,40,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2023-04-27
4,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-03-04,Parts per million,None,17,100.0,0.049647,0.063,10,77,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2023-04-27

In [10]:
concat_df1.shape

(382475, 29)

In [11]:
# Converting string back to date
def convert_string_to_date(input_str):
    """
    This function converts string back to date using strptime method
    """
    return datetime.strptime(input_str,"%Y-%m-%d")
# Applying the function to Admission and Discharge data to convert them to Date datatype
concat_df1["Date Local"]=concat_df1["Date Local"].apply(convert_string_to_date)

In [12]:
concat_df1.head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,Pollutant Standard,Date Local,Units of Measure,Event Type,Observation Count,Observation Percent,Arithmetic Mean,1st Max Value,1st Max Hour,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
0,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-02-28,Parts per million,None,1,6.0,0.038000,0.038,23,35,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2023-04-27
1,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-03-01,Parts per million,None,17,100.0,0.037235,0.054,12,50,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2023-04-27
2,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-03-02,Parts per million,None,17,100.0,0.038235,0.055,12,51,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2023-04-27
3,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-03-03,Parts per million,None,9,53.0,0.024333,0.043,15,40,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2023-04-27
4,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-03-04,Parts per million,None,17,100.0,0.049647,0.063,10,77,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE, ALABAMA",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2023-04-27

In [13]:
concat_df1=concat_df1.drop(["Datum","Parameter Name","Sample Duration","Pollutant Standard"
                        ,"Units of Measure","Event Type","Method Name","Local Site Name",
                        "Address","State Name","County Name","City Name","CBSA Name","Date of Last Change"
                        ,"POC","Method Code","Observation Count","Observation Percent","Latitude",
                        "Longitude","1st Max Value","1st Max Hour","Parameter Code"],axis=1)
concat_df1=concat_df1.fillna(0)

In [14]:
concat_df1.head()

   State Code  County Code  Site Num Date Local  Arithmetic Mean  AQI
0           1            3        10 2022-02-28         0.038000   35
1           1            3        10 2022-03-01         0.037235   50
2           1            3        10 2022-03-02         0.038235   51
3           1            3        10 2022-03-03         0.024333   40
4           1            3        10 2022-03-04         0.049647   77

In [15]:
concat_df1.shape

(382475, 6)

In [16]:
df_88502=df_88502.drop(["Datum","Parameter Name","Sample Duration","Pollutant Standard"
                        ,"Units of Measure","Event Type","Method Name","Local Site Name",
                        "Address","State Name","County Name","City Name","CBSA Name","Date of Last Change"
                        ,"POC","Method Code","Observation Count","Observation Percent","Latitude",
                        "Longitude","1st Max Value","1st Max Hour","AQI","Parameter Code"],axis=1)
df_88502=df_88502.fillna(0)
###
NO2_df=NO2_df.drop(["Datum","Parameter Name","Sample Duration","Pollutant Standard"
                        ,"Units of Measure","Event Type","Method Name","Local Site Name",
                        "Address","State Name","County Name","City Name","CBSA Name","Date of Last Change"
                        ,"POC","Method Code","Observation Count","Observation Percent","Latitude",
                        "Longitude","1st Max Value","1st Max Hour","AQI","Parameter Code"],axis=1)
NO2_df=NO2_df.fillna(0)
####
CO_df=CO_df.drop(["Datum","Parameter Name","Sample Duration","Pollutant Standard"
                        ,"Units of Measure","Event Type","Method Name","Local Site Name",
                        "Address","State Name","County Name","City Name","CBSA Name","Date of Last Change"
                        ,"POC","Method Code","Observation Count","Observation Percent","Latitude",
                        "Longitude","1st Max Value","1st Max Hour","AQI","Parameter Code"],axis=1)
CO_df=CO_df.fillna(0)
####
SO2_df=SO2_df.drop(["Datum","Parameter Name","Sample Duration","Pollutant Standard"
                        ,"Units of Measure","Event Type","Method Name","Local Site Name",
                        "Address","State Name","County Name","City Name","CBSA Name","Date of Last Change"
                        ,"POC","Method Code","Observation Count","Observation Percent","Latitude",
                        "Longitude","1st Max Value","1st Max Hour","AQI","Parameter Code"],axis=1)
SO2_df=SO2_df.fillna(0)
####
temp_df=temp_df.drop(["Datum","Parameter Name","Sample Duration","Pollutant Standard"
                        ,"Units of Measure","Event Type","Method Name","Local Site Name",
                        "Address","State Name","County Name","City Name","CBSA Name","Date of Last Change"
                        ,"POC","Method Code","Observation Count","Observation Percent","Latitude",
                        "Longitude","1st Max Value","1st Max Hour","AQI","Parameter Code"],axis=1)
temp_df=temp_df.fillna(0)
###
df_88101=df_88101.drop(["Datum","Parameter Name","Sample Duration","Pollutant Standard"
                        ,"Units of Measure","Event Type","Method Name","Local Site Name",
                        "Address","State Name","County Name","City Name","CBSA Name","Date of Last Change"
                        ,"POC","Method Code","Observation Count","Observation Percent","Latitude",
                        "Longitude","1st Max Value","1st Max Hour","AQI","Parameter Code"],axis=1)
df_88101=df_88101.fillna(0)
###
df_81101=df_81101.drop(["Datum","Parameter Name","Sample Duration","Pollutant Standard"
                        ,"Units of Measure","Event Type","Method Name","Local Site Name",
                        "Address","State Name","County Name","City Name","CBSA Name","Date of Last Change"
                        ,"POC","Method Code","Observation Count","Observation Percent","Latitude",
                        "Longitude","1st Max Value","1st Max Hour","AQI","Parameter Code"],axis=1)
df_81101=df_81101.fillna(0)
###
df_86101=df_86101.drop(["Datum","Parameter Name","Sample Duration","Pollutant Standard"
                        ,"Units of Measure","Event Type","Method Name","Local Site Name",
                        "Address","State Name","County Name","City Name","CBSA Name","Date of Last Change"
                        ,"POC","Method Code","Observation Count","Observation Percent","Latitude",
                        "Longitude","1st Max Value","1st Max Hour","AQI","Parameter Code"],axis=1)
df_86101=df_86101.fillna(0)
###
df_PM10SPEC=df_PM10SPEC.drop(["Datum","Parameter Name","Sample Duration","Pollutant Standard"
                        ,"Units of Measure","Event Type","Method Name","Local Site Name",
                        "Address","State Name","County Name","City Name","CBSA Name","Date of Last Change"
                        ,"POC","Method Code","Observation Count","Observation Percent","Latitude",
                        "Longitude","1st Max Value","1st Max Hour","AQI","Parameter Code"],axis=1)
df_PM10SPEC=df_PM10SPEC.fillna(0)
###
press_df=press_df.drop(["Datum","Parameter Name","Sample Duration","Pollutant Standard"
                        ,"Units of Measure","Event Type","Method Name","Local Site Name",
                        "Address","State Name","County Name","City Name","CBSA Name","Date of Last Change"
                        ,"POC","Method Code","Observation Count","Observation Percent","Latitude",
                        "Longitude","1st Max Value","1st Max Hour","AQI","Parameter Code"],axis=1)
press_df=press_df.fillna(0)
###
wind_df=wind_df.drop(["Datum","Parameter Name","Sample Duration","Pollutant Standard"
                        ,"Units of Measure","Event Type","Method Name","Local Site Name",
                        "Address","State Name","County Name","City Name","CBSA Name","Date of Last Change"
                        ,"POC","Method Code","Observation Count","Observation Percent","Latitude",
                        "Longitude","1st Max Value","1st Max Hour","AQI","Parameter Code"],axis=1)
wind_df=wind_df.fillna(0)
###
RH_df=RH_df.drop(["Datum","Parameter Name","Sample Duration","Pollutant Standard"
                        ,"Units of Measure","Event Type","Method Name","Local Site Name",
                        "Address","State Name","County Name","City Name","CBSA Name","Date of Last Change"
                        ,"POC","Method Code","Observation Count","Observation Percent","Latitude",
                        "Longitude","1st Max Value","1st Max Hour","AQI","Parameter Code"],axis=1)
RH_df=RH_df.fillna(0)

In [17]:
df_88502["Date Local"]=df_88502["Date Local"].apply(convert_string_to_date)
NO2_df["Date Local"]=NO2_df["Date Local"].apply(convert_string_to_date)
CO_df["Date Local"]=CO_df["Date Local"].apply(convert_string_to_date)
SO2_df["Date Local"]=SO2_df["Date Local"].apply(convert_string_to_date)
temp_df["Date Local"]=temp_df["Date Local"].apply(convert_string_to_date)
df_88101["Date Local"]=df_88101["Date Local"].apply(convert_string_to_date)
df_81101["Date Local"]=df_81101["Date Local"].apply(convert_string_to_date)
df_86101["Date Local"]=df_86101["Date Local"].apply(convert_string_to_date)
df_PM10SPEC["Date Local"]=df_PM10SPEC["Date Local"].apply(convert_string_to_date)
press_df["Date Local"]=press_df["Date Local"].apply(convert_string_to_date)
wind_df["Date Local"]=wind_df["Date Local"].apply(convert_string_to_date)
RH_df["Date Local"]=RH_df["Date Local"].apply(convert_string_to_date)

In [18]:
concat_df1=concat_df1.rename(columns={"Arithmetic Mean":"ozone_mean"})
df_88502=df_88502.rename(columns={"Arithmetic Mean":"88502_mean"})
NO2_df=NO2_df.rename(columns={"Arithmetic Mean":"NO2_mean"})
CO_df=CO_df.rename(columns={"Arithmetic Mean":"CO_mean"})
SO2_df=SO2_df.rename(columns={"Arithmetic Mean":"SO2_mean"})
temp_df=temp_df.rename(columns={"Arithmetic Mean":"temp_mean"})
df_88101=df_88101.rename(columns={"Arithmetic Mean":"88101_mean"})
df_81101=df_81101.rename(columns={"Arithmetic Mean":"81101_mean"})
df_86101=df_86101.rename(columns={"Arithmetic Mean":"86101_mean"})
df_PM10SPEC=df_PM10SPEC.rename(columns={"Arithmetic Mean":"PM10SPEC_mean"})
press_df=press_df.rename(columns={"Arithmetic Mean":"press_mean"})
wind_df=wind_df.rename(columns={"Arithmetic Mean":"wind_mean"})
RH_df=RH_df.rename(columns={"Arithmetic Mean":"RH_mean"})

In [19]:
merge1_df=pd.merge(concat_df1,NO2_df,on=["State Code","County Code","Site Num","Date Local"])
merge1_df=merge1_df.fillna(merge1_df.mean())

In [20]:
merge2_df=pd.merge(merge1_df,SO2_df,on=["State Code","County Code","Site Num","Date Local"])
merge2_df=merge2_df.fillna(merge2_df.mean())

In [21]:
merge3_df=pd.merge(merge2_df,CO_df,on=["State Code","County Code","Site Num","Date Local"])
merge3_df=merge3_df.fillna(merge3_df.mean())

In [22]:
merge4_df=pd.merge(merge3_df,temp_df,on=["State Code","County Code","Site Num","Date Local"])
merge4_df=merge4_df.fillna(merge4_df.mean())

In [23]:
merge5_df=pd.merge(merge4_df,df_88502,on=["State Code","County Code","Site Num","Date Local"])
merge5_df=merge5_df.fillna(merge5_df.mean())

In [24]:
merge6_df=pd.merge(merge5_df,df_88101,on=["State Code","County Code","Site Num","Date Local"])
merge6_df=merge6_df.fillna(merge6_df.mean())

In [25]:
merge7_df=pd.merge(merge6_df,df_81101,on=["State Code","County Code","Site Num","Date Local"])
merge7_df=merge7_df.fillna(merge7_df.mean())

In [26]:
merge8_df=pd.merge(merge7_df,df_86101,on=["State Code","County Code","Site Num","Date Local"])
merge8_df=merge8_df.fillna(merge8_df.mean())

In [27]:
merge9_df=pd.merge(merge8_df,df_PM10SPEC,on=["State Code","County Code","Site Num","Date Local"])
merge9_df=merge9_df.fillna(merge9_df.mean())

In [28]:
merge10_df=pd.merge(merge9_df,press_df,on=["State Code","County Code","Site Num","Date Local"])
merge10_df=merge10_df.fillna(merge10_df.mean())

In [29]:
merge11_df=pd.merge(merge10_df,wind_df,on=["State Code","County Code","Site Num","Date Local"])
merge11_df=merge11_df.fillna(merge11_df.mean())

In [30]:
merge12_df=pd.merge(merge11_df,RH_df,on=["State Code","County Code","Site Num","Date Local"])
merge12_df=merge12_df.fillna(merge12_df.mean())

In [31]:
merge12_df.shape

(228120, 18)

In [32]:
merge12_df = merge12_df.drop_duplicates(keep='last')

In [33]:
merge12_df.shape

(200944, 18)

In [34]:
merge12_df.shape

(200944, 18)

In [35]:
merge12_df["year"]=merge12_df["Date Local"].dt.year
merge12_df["month"]=merge12_df["Date Local"].dt.month
merge12_df["date"]=merge12_df["Date Local"].dt.day
merge12_df=merge12_df.drop(["Date Local"],axis=1)

In [36]:
"""
merge3_df=merge3_df.rename(columns={"Arithmetic Mean_x":"Ozone_mean",
                         "Arithmetic Mean_y":"particle_mean",
                                   "AQI_x":"AQI"})
                                   """

'\nmerge3_df=merge3_df.rename(columns={"Arithmetic Mean_x":"Ozone_mean",\n                         "Arithmetic Mean_y":"particle_mean",\n                                   "AQI_x":"AQI"})\n                                   '

In [37]:
#merge1_df=merge1_df.drop(["Parameter Code_x","Parameter Code_y","AQI_y"],axis=1)
#merge3_df=merge3_df.drop(["Parameter Code_x","Parameter Code_y","AQI_y"],axis=1)

In [38]:
merge12_df.head()

,State Code,County Code,Site Num,ozone_mean,AQI,NO2_mean,SO2_mean,CO_mean,temp_mean,88502_mean,88101_mean,81101_mean,86101_mean,PM10SPEC_mean,press_mean,wind_mean,RH_mean,year,month,date
0,1,73,23,0.028059,33,5.041667,-0.383333,0.179167,63.625,6.6,7.7,17,7.129167,17.85,994.2125,5.362500,88.625,2022,4,17
1,1,73,23,0.028059,33,5.041667,-0.383333,0.179167,63.625,6.6,7.7,17,7.129167,17.85,994.2125,129.708333,88.625,2022,4,17
2,1,73,23,0.028059,33,5.041667,-0.383333,0.179167,63.625,6.6,7.7,17,7.129167,10.71,994.2125,5.362500,88.625,2022,4,17
3,1,73,23,0.028059,33,5.041667,-0.383333,0.179167,63.625,6.6,7.7,17,7.129167,10.71,994.2125,129.708333,88.625,2022,4,17
4,1,73,23,0.028059,33,5.041667,-0.383333,0.179167,63.625,6.6,7.7,17,4.000000,17.85,994.2125,5.362500,88.625,2022,4,17

In [39]:
# Defining the Features and Target for the Mutual Info regression and for Model Building
features=merge12_df.drop(labels=['AQI'], axis=1)
# Setting the target variable as the Electricity Cost in Dollars
target=merge12_df['AQI']

In [40]:
# Creating training and test datasets using 80:20 split
X_train, X_test, y_train, y_test = train_test_split(features,target,test_size=0.2,random_state=34)

In [41]:
scaler = StandardScaler()

In [42]:
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [43]:
regr = LinearRegression()
regr.fit(X_train, y_train)

LinearRegression()

In [44]:
print(regr.score(X_test, y_test))

0.8026131286483337